# configure the parameters
dir_patients: "C:/Users/mohsen/Desktop/Postdoc_Upa/Datasets/GaitAnalysis/src/"
dir_dist: "C:/Users/mohsen/Desktop/Postdoc_Upa/Datasets/GaitAnalysis/dst"
path_csv_file: "C:/Users/mohsen/Desktop/Postdoc_Upa/Datasets/GaitAnalysis/ORL_skeletons_lookup - labels.csv"

keypoints: ['nose','left_eye','right_eye','left_ear','right_ear','left_shoulder','right_shoulder','left_elbow',
                'right_elbow','left_wrist','right_wrist','left_hip','right_hip','left_knee', 'right_knee', 'left_ankle','right_ankle']


label_file_name_: "Notice.xml" 
data_file_name_: "data.File"


dataset_params:
  WINDOW_SIZE: 100
  features_size: 70
  image_need_crop: True
  scale_w: 0.5
  scale_h: 1
  ZERO_PADDING: True
  person_thresh: 0.8
  keypoint_threshold: 0
  num_keypoints: 17
  all_possible_features: True
  # '1': detection, '2': detection with missing points
  # '3': one frame tracking, '4': five frames tracking
  mode: "1"